language: crystal
cache: shards
crystal:
  - latest
  - nightly

before_install:
  - sudo apt-get -y install libglfw3-dev mesa-common-dev

addons:
  apt:
    update: true

script:
  - crystal spec -D ci --error-trace
  - crystal tool format --check

after_success:
  - crystal docs

# TODO: deploy docs somewhere